image: node:latest

stages:
  - setup
  - test
  - deploy

cache:
  paths:
    - node_modules
  key: "$CI_BUILD_REPO"

setup:
  stage: setup
  script:
    - echo "Building _version=$BUNDLE_REF"
    - npm -v
    - node -v
    - echo "Installing dependancies"
    - npm install --cache-min=99999999 > /dev/null
  artifacts:
    name: "${CI_JOB_STAGE}_${CI_COMMIT_REF_NAME}"
    paths:
      - node_modules
    expire_in: 1 day

test:
  stage: test
  script:
    - npm run lint

deploy:
  stage: deploy
  script:
    - echo "Deploying to production"
    - firebase use one-time-password-b1f2e --token $FIREBASE_TOKEN
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN
  when: manual

## Hold scripts
# firebase use one-time-password-b1f2e --token $FIREBASE_TOKEN
#  firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN